# version: "3.8"

# services:
#   db:
#     image: postgres:15
#     container_name: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: harish
#       POSTGRES_DB: DEMO_SESSION
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "6543:5432"

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nest-docker-postgres
#     restart: always
#     environment:
#       PORT: 5000
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: harish
#       DB_NAME: DEMO_SESSION
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: nest-pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db

# volumes:
#   pgdata:
